# Generated by Django 4.1 on 2022-08-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_category_id_alter_new_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='photo',
            field=models.ImageField(blank=True, default='book.jgp', upload_to=''),
        ),
    ]
