# Generated by Django 4.1 on 2022-08-17 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_new_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='photo',
            field=models.ImageField(default='book.jpg', upload_to=''),
        ),
    ]
